apps/home/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'home_blueprint',
    __name__,
    url_prefix=''
)

apps/home/routes.py
import os
from apps.home import blueprint
from flask import render_template, request , flash, url_for, request, redirect,send_from_directory,abort
from flask_login import login_required
from apps.home.models import Model
from flask import send_file
from flask_login import (
    current_user,
    login_user,
    logout_user
)
import logging
from flask import jsonify
from apps.authentication.forms import LoginForm, CreateAccountForm
import sqlite3
import uuid
from datetime import datetime
import json
from dotenv import load_dotenv
load_dotenv()
DB_FOLDER = "./apps/DB/"



@blueprint.route('/index')
@login_required
def index():
    Model_obj = Model()
    # dash_data = Model_obj.Dash_getScan_details(current_user)
    agent_data = Model_obj.get_agents_count(current_user)
    agent_count = agent_data['agent_count']
    projects = Model_obj.list_projects_index(current_user)
   
    progress_count = Model_obj.get_progress_count(current_user)
    engineers_count = Model_obj.get_engineers_count(current_user)
    project_count = Model_obj.get_project_count(current_user)  # Add this line
    
    return render_template('home/index.html', 
                           segment='index', 
                        #    data=dash_data, 
                           agent_count=agent_count, 
                           progress_count=progress_count,
                           engineers_count=engineers_count,
                           project_count=project_count,projects=projects)  # Pass project_count to the template

@blueprint.route('/delete-item', methods=['POST'])
def delete_item():
    # Get the data sent in the request
    data = request.get_json()
    print("Received data:", data)  # Debugging - print the received data

    # Get the key from the received data
    key = data.get('key')
    if not key:
        return jsonify({"status": "error", "message": "Invalid Key"}), 400

    try:
        # Interact with the Model to delete the item using the key
        Model_obj = Model()
        delete_result = Model_obj.delete_item(key)  # Assuming you have a method to delete by key
        
        if delete_result['status'] == 'success':
            return jsonify({"status": "success", "message": delete_result['message']})
        else:
            return jsonify({"status": "error", "message": delete_result['message']}), 400
    except Exception as e:
        # Handle unexpected errors
        return jsonify({"status": "error", "message": f"An error occurred: {str(e)}"}), 500

@blueprint.route('/Dut_Configuration', methods=['GET', 'POST'])
@login_required
def Dut_Configuration():
    Model_obj = Model()
    
    # Fetch all EUT configurations at the start
    eut_configurations = Model_obj.list_dut_configurations(current_user)
    # print("eut_configurations:",eut_configurations)

    if request.method == 'POST':
        type_req = request.form['type']
        if type_req == "eut_conf":
            try:      
                model_no = request.form['ModelNo']
                product_name = request.form['ProductName']
                manufacturer = request.form['Mfg']
                serial_no = request.form['SN']
                software_version = request.form['SW_Version']
                hardware_version = request.form['HW_Version']
                product_no = request.form['product_no']

                Front_img_file = request.files['front_img']
                Front_img_data = Front_img_file.read() if Front_img_file else None

                Side_img_file = request.files['Side_img']
                Side_img_data = Side_img_file.read() if Side_img_file else None

                Port_img_file = request.files['Port_img']
                Port_img_data = Port_img_file.read() if Port_img_file else None

                response = Model_obj.insert_EUTConfiguration(
                    str(current_user), model_no, product_name, manufacturer, 
                    serial_no, software_version, hardware_version, product_no, 
                    Front_img_data, Side_img_data, Port_img_data
                )

                if response == True:
                    # Success
                    flash("You have successfully created DUT Configuration", "success")
                else:
                    # If there's an error, extract the message from the response
                    flash(response['message'], "error")
                # Re-fetch EUT configurations to show the updated list
                eut_configurations = Model_obj.list_dut_configurations(current_user)
                return render_template('home/dut_configuration.html', segment='duts', eut_configurations=eut_configurations)

            except Exception as e:
                flash("Failed to create DUT main Configuration: " + str(e), "error")
                return render_template('home/dut_configuration.html', segment='duts', eut_configurations=eut_configurations)

    try:
        if 'delete' in request.args:
            delete = request.args['delete']
            delete_result = Model_obj.Delete_DUT(current_user, delete)

            if delete_result['status'] == "success":
                flash(delete_result['message'], "success")
            else:
                flash(delete_result['message'], "error")

            eut_configurations = Model_obj.list_dut_configurations(current_user)
            return render_template('home/dut_configuration.html', segment='duts', eut_configurations=eut_configurations)

    except Exception as e:
        flash("Failed to delete DUT: " + str(e), "error")


    return render_template('home/dut_configuration.html', segment='duts', eut_configurations=eut_configurations)



@blueprint.route('/Dut_Configuration/edit/<dut_id>', methods=['POST'])
def edit_dut_configuration(dut_id):
    try:
        Model_obj = Model()
     
        # print("dut_id:",dut_id)
        model_no = request.form.get('ModelNo')
        product_name = request.form.get('ProductName')
        manufacturer = request.form.get('Manufacturer')
        serial_no = request.form.get('SerialNo')
        software_version = request.form.get('SoftwareVersion')
        hardware_version = request.form.get('HardwareVersion')
        # product_no = request.form.get('product_no')

        # Front_img_file = request.files.get('front_img')
        # Side_img_file = request.files.get('Side_img')
        # Port_img_file = request.files.get('Port_img')

        # Front_img_data = Front_img_file.read() if Front_img_file else None
        # Side_img_data = Side_img_file.read() if Side_img_file else None
        # Port_img_data = Port_img_file.read() if Port_img_file else None

        Model_obj.update_EUTConfiguration(
            dut_id, str(current_user), model_no, product_name, manufacturer,
            serial_no, software_version, hardware_version
        )

        flash("You have successfully updated the EUT Configuration", "success")
        return redirect(url_for('home_blueprint.Dut_Configuration')) 
    except Exception as e:
        logging.error(f"Error updating EUT Configuration: {e}")
        return "Bad Request", 400

@blueprint.route('/reports', methods=['GET'])
@login_required
def file_uploads():
    Model_obj = Model()
    uploads_data = Model_obj.get_file_uploads(current_user)
   
    # print(f"File Uploads Data: {uploads_data}")
    
    return render_template('home/scans.html', uploads=uploads_data)

@blueprint.route('/delete_report', methods=['POST'])
@login_required
def delete_report():
    scan_id = request.form.get('scan_id')
    if scan_id:
        Model_obj = Model()
        delete_result = Model_obj.delete_report(scan_id)

        if delete_result['status'] == 'success':
            return jsonify({"status": "success", "message": delete_result['message']})
        else:
            return jsonify({"status": "error", "message": delete_result['message']}), 400
    else:
        return jsonify({"status": "error", "message": "Invalid scan ID"}), 400


@blueprint.route('/view_report_files', methods=['GET'])
def view_report_files():
    scan_id = request.args.get('id')  # Fetch scan_id from request
    # print("scan_id:", scan_id)
    Model_obj = Model()

    # Fetch the report directory path for the given scan_id
    scan_data = Model_obj.get_report_by_scanid(scan_id)

    if not scan_data:
        return render_template('home/scan_report.html', files=[], message="Scan not found.")

    report_directory = scan_data[0][0]  # Assuming repo_dir is the 1st field in the record

    report_directory = scan_data[0][0]
    
    # Define image extensions to check against
    image_extensions = {'.jpg', '.jpeg', '.png', '.gif', '.bmp', '.tiff'}  
    try:
        all_files = os.listdir(report_directory)

        # Separate files
        files = [file for file in all_files if not any(file.lower().endswith(ext) for ext in image_extensions)]
        images = [file for file in all_files if any(file.lower().endswith(ext) for ext in image_extensions)]
        
        # Get basenames without extensions
        image_basenames = [os.path.splitext(image)[0] for image in images]

        show_table = not bool(images)  # Only show table if there are no images
    except FileNotFoundError:
        files = []
        images = []
        image_basenames = []  # Ensure this is empty on error
        show_table = True

    # Render template with separated file lists and show_table flag
    return render_template(
        'home/scan_report.html',
        files=files,
        images=images,
        image_basenames=image_basenames,  # Pass the basenames to the template
        show_table=show_table,
        report_directory=report_directory,
        id=scan_id
    )
# @blueprint.route('/view_subtype_report_files', methods=['GET'])
# def view_subtype_report_files():
#     scan_id = request.args.get('id')  # Fetch scan_id from request
#     print("scan_id:", scan_id)
#     Model_obj = Model()

#     # Fetch the report directory path for the given scan_id

apps/templates/home/failure.html
{% extends "layouts/base.html" %}

{% block title %} Bla
nk Page {% endblock %} 

<!-- Element injected in the BODY element -->
{% block body_class %} sidebar-mini pace-primary {% endblock body_class %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/assets/plugins/fontawesome-free/css/all.min.css">
  <!-- pace-progress -->
  <link rel="stylesheet" href="/static/assets/plugins/pace-progress/themes/black/pace-theme-flat-top.css">
  <!-- adminlte-->
  <link rel="stylesheet" href="/static/assets/css/adminlte.min.css">

{% endblock stylesheets %}

{% block content %}  

<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <!-- Header -->
              
            
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Start</li>
          </ol>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">

    <!-- Default box -->
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><b><i class="fa fa-thumbs-down"></i> Failure</b></h3>
       
      </div>
      <div class="card-body">
        <div class="col-sm-4 mx-auto" class="col d-flex justify-content-center">
          <div class="info-box">
            <span class="info-box-icon btn-danger"><i class="far fa-thumbs-down"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">{{data}}</span>
            </div>              
          </div>
        </div>
      </div>
      <!-- /.card-body -->
      
      <!-- /.card-footer-->
    </div>
    <!-- /.card -->

  </section>
  <!-- /.content -->
</div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <!-- jQuery -->
  <script src="/static/assets/plugins/jquery/jquery.min.js"></script>
  <!-- Bootstrap 4 -->
  <script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- pace-progress -->
  <script src="/static/assets/plugins/pace-progress/pace.min.js"></script>
  <!-- AdminLTE App -->
  <script src="/static/assets/js/adminlte.min.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="/static/assets/js/demo.js"></script>

{% endblock javascripts %}

apps/templates/home/scans.html
{% extends "layouts/base.html" %} {% block title %} Reports {% endblock %} {%
block body_class %} {% endblock body_class %} {% block stylesheets %}
<!-- Google Font: Source Sans Pro -->
<link
  rel="stylesheet"
  href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback"
/>
<link
  rel="stylesheet"
  href="/static/assets/plugins/fontawesome-free/css/all.min.css"
/>
<link
  rel="stylesheet"
  href="/static/assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css"
/>
<link
  rel="stylesheet"
  href="/static/assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css"
/>
<link rel="stylesheet" href="/static/assets/css/adminlte.min.css" />
{% endblock stylesheets %} {% block content %}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header" id="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>Reports</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item active">Reports</li>
          </ol>
        </div>
      </div>
    </div>
    <!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <!-- Scan Table -->
          <div class="card" id="scan-table">
            <div class="card-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th class="text-center">S.No</th>
                    <th class="text-center">Date</th>
                    <th class="text-center">Time</th>
                    <th class="text-center">Project Name</th>
                    <th class="text-center">Test Case</th>
                    <th class="text-center">Agent Name</th>
                    <th class="text-center">Engineer Names</th>
                    <th class="text-center">View</th>
                    <th class="text-center">Delete</th>
                  </tr>
                </thead>
                <tbody>
                  {% for upload in uploads %}
                  <tr>
                    <td class="text-center">{{ loop.index }}</td>
                    <!-- Upload Date -->
                    <td class="text-center">{{ upload[1] }}</td>
                    <!-- Upload Time -->
                    <td class="text-center">{{ upload[2] }}</td>
                    <!-- Project Name -->
                    <td class="text-center">{{ upload[3] }}</td>
                    <!-- Test Case -->
                    <td class="text-center">{{ upload[4] }}</td>

                    <!-- Agent Name -->
                    <td class="text-center">{{ upload[0] }}</td>
                    <!-- Engineer names list -->
                    <td class="text-center">
                      {% if upload[10] %} {{ upload[10] | join(', ') }} {% else
                      %} No engineers {% endif %}
                    </td>
                    <td class="text-center">
                      <form
                        action="{{ url_for('home_blueprint.view_subtype_report_files') }}"
                        method="POST"
                        style="display: inline"
                      >
                        <input
                          type="hidden"
                          name="project_name"
                          value="{{ upload[3] }}"
                        />
                        <input type="hidden" name="id" value="{{ upload[7]}}" />
                        <input
                          type="hidden"
                          name="project_type"
                          value="{{ upload[9]}}"
                        />
                        <input
                          type="hidden"
                          name="project_dut"
                          value="{{ upload[8]}}"
                        />
                        <input
                          type="hidden"
                          name="subtype_name"
                          value="{{ upload[4] }}"
                        />
                        <button
                          type="submit"
                          style="
                            border: none;
                            background: transparent;
                            margin-left: 5px;
                          "
                        >
                          <i class="fas fa-eye" style="color: #007bff"></i>
                        </button>
                      </form>
                    </td>

                    <td class="text-center">
                      <a
                        class="btn btn-danger btn-sm"
                        onclick="confirmDelete('{{ upload[7] }}')"
                      >
                        <i class="fas fa-trash"></i> Delete
                      </a>
                    </td>
                  </tr>
                  {% else %}
                  <tr>
                    <td colspan="9" class="text-center">No uploads found.</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>

          <!-- Report Table, initially hidden -->
          <div id="report-section" style="display: none">
            <section class="content-header">
              <div class="container-fluid px-0">
                <div class="row mb-2">
                  <div class="col-sm-6">
                    <h1>Report Files</h1>
                  </div>
                  <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                      <li class="breadcrumb-item"><a href="/">Home</a></li>
                      <li class="breadcrumb-item">
                        <a href="#" id="back-button">Reports</a>
                      </li>
                      <li class="breadcrumb-item active">Files</li>
                    </ol>
                  </div>
                </div>
              </div>
            </section>
            <div class="card">
              <div class="card-body" id="report-container">
                <!-- Files content will be loaded here -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
{% endblock content %} {% block javascripts %}
<script src="/static/assets/plugins/jquery/jquery.min.js"></script>
<script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/static/assets/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="/static/assets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="/static/assets/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="/static/assets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="/static/assets/js/adminlte.min.js"></script>

<script>
  $(function () {
    // Initialize DataTable
    $("#example1").DataTable({
      responsive: true,
      autoWidth: false,
    });

    // View report files on clicking 'View Files'
    $(document).on("click", ".view-report", function (e) {
      e.preventDefault();
      var id = $(this).data("id");

      $.ajax({
        url: "{{ url_for('home_blueprint.view_report_files') }}",
        type: "GET",
        data: { id: id },
        success: function (response) {
          $("#content-header").hide();
          $("#scan-table").hide();
          $("#report-section").show();
          $("#report-container").html(response);
        },
        error: function (xhr, status, error) {
          console.error("Error:", error);
        },
      });
    });

    // Go back to scan table
    $("#back-button").click(function () {
      $("#report-section").hide();
      $("#scan-table").show();
      $("#content-header").show();
    });
  });
</script>
<script>
  function confirmDelete(scanId) {
    Swal.fire({
      title: "Are you sure?",
      text: "You won't be able to revert this!",
      icon: "warning",
      showCancelButton: true,
      confirmButtonColor: "#d33",
      cancelButtonColor: "#3085d6",
      confirmButtonText: "Yes, delete it!",
      cancelButtonText: "Cancel",
    }).then((result) => {
      if (result.isConfirmed) {
        // Perform the delete action via AJAX
        $.ajax({
          url: "{{ url_for('home_blueprint.delete_report') }}", // Your Flask route for deleting
          type: "POST",
          data: { scan_id: scanId },
          success: function (response) {
            Swal.fire({
              title: "Deleted!",
              text: "Your report has been deleted.",
              icon: "success",
              timer: 2000,
              showConfirmButton: false,
            }).then(() => {
              // Reload the page or remove the deleted row
              location.reload();
            });
          },
          error: function (xhr, status, error) {
            Swal.fire({
              title: "Error",
              text: "Something went wrong: " + error,
              icon: "error",
            });
          },
        });
      }
    });
  }
</script>

{% endblock javascripts %}

apps/templates/home/subtype_details.html
{% extends "layouts/base.html" %} {% block title %} Agent Management {% endblock
%} {% block stylesheets %}
<link
  rel="stylesheet"
  href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback"
/>
<link
  rel="stylesheet"
  href="/static/assets/plugins/fontawesome-free/css/all.min.css"
/>
<link
  rel="stylesheet"
  href="/static/assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css"
/>
<link
  rel="stylesheet"
  href="/static/assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css"
/>
<link rel="stylesheet" href="/static/assets/css/adminlte.min.css" />
{% endblock stylesheets %} {% block content %}

<div class="content-wrapper">
  <!-- Page header -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>{{ project_name }}</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item">
              <form action="{{ url_for('home_blueprint.view_all_subtype') }}" method='POST'>
                <input type="hidden" name="project_name" value="{{ project_name }}">
                <input type="hidden" name="project_type" value="{{ project_type }}">
                <input type="hidden" name="project_dut" value="{{ project_dut }}">
                
                <button
                  type="submit"
                  style="border: none; background: transparent; color: blue"
                >
                  Back
                </button>
              </form>
           
          </ol>
        </div>
      </div>
    </div>
  </section>

    <!-- Content Wrapper. Contains page content -->
    <!-- <div class="content-wrapper"> -->
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <!-- Scan Table -->
            <div class="card" id="scan-table">
              <div class="card-body">
                <table id="example2" class="table table-bordered table-striped">
                  <thead>
                    <tr>
                      <th class="text-center">S.No</th>
                      <th class="text-center">Date</th>
                      <th class="text-center">Time</th>
                      <!-- <th class="text-center">Project Name</th>
                    <th class="text-center">Test Case</th> -->
                      <th class="text-center">Agent Name</th>
                      <th class="text-center">Engineer Names</th>
                      <th class="text-center">View</th>
                      <th class="text-center">Delete</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for upload in uploads %}
                    <tr>
                      <td class="text-center">{{ loop.index }}</td>
                      <!-- Upload Date -->
                      <td class="text-center">{{ upload[1] }}</td>
                      <!-- Upload Time -->
                      <td class="text-center">{{ upload[2] }}</td>
                      <!-- Project Name -->
                      <!-- <td class="text-center">{{ upload[3] }}</td> -->
                      <!-- Test Case -->
                      <!-- <td class="text-center">{{ upload[4] }}</td> -->

                      <!-- Agent Name -->
                      <td class="text-center">{{ upload[0] }}</td>
                      <!-- Engineer names list -->
                      <td class="text-center">
                        {% if upload[8] %} {{ upload[8] | join(', ') }} {% else
                        %} No engineers {% endif %}
                      </td>
                      <td class="text-center">
                        <form action="{{ url_for('home_blueprint.view_subtype_report_files') }}" method="POST" style="display: inline;">
                          <input type="hidden" name="project_name" value="{{ project_name }}">
                          <input type="hidden" name="id" value="{{ upload[7]}}">
                          <input type="hidden" name="project_type" value="{{ project_type }}">
                          <input type="hidden" name="project_dut" value="{{ project_dut }}">
                          <input type="hidden" name="subtype_name" value="{{ subtype_name }}">
                          <button type="submit" style="border: none; background: transparent; margin-left: 5px;">
                            <i class="fas fa-eye" style="color: #007bff"></i>
                          </button>
                        </form>
                       
                      </td>
                      <td class="text-center">
                        <a
                          class="btn btn-danger btn-sm"
                          onclick="confirmDelete('{{ upload[7] }}')"
                        >
                          <i class="fas fa-trash"></i> Delete
                        </a>
                      </td>
                    </tr>
                    {% else %}
                    <tr>
                      <td colspan="7" class="text-center">
                        No file uploads available.
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>

            <!-- Report Table, initially hidden -->
            <div id="report-section" style="display: none">
              <div class="card">
                <div class="card-body" id="report-container">
                  <!-- Files content will be loaded here -->
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</div>
{% endblock content %} 
{% block javascripts %}
<script src="/static/assets/plugins/jquery/jquery.min.js"></script>
<script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/static/assets/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="/static/assets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="/static/assets/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="/static/assets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="/static/assets/js/adminlte.min.js"></script>

<script>
  $(function () {
    // Initialize DataTable
    $("#example2").DataTable({
      responsive: true,
      autoWidth: false,
    });

    // View report files on clicking 'View Files'
    $(document).on("click", ".view-report", function (e) {
      e.preventDefault();
      var id = $(this).data("id");

      $.ajax({
        url: "{{ url_for('home_blueprint.view_subtype_report_files') }}",
        type: "GET",
        data: { id: id },
        success: function (response) {
          $("#report-section").show();
          $("#report-container").html(response);
        },
        error: function (xhr, status, error) {
          console.error("Error:", error);
        },
      });
    });
  });
</script>

<script>
  function confirmDelete(scanId) {
    Swal.fire({
      title: "Are you sure?",
      text: "You won't be able to revert this!",
      icon: "warning",
      showCancelButton: true,
      confirmButtonColor: "#d33",
      cancelButtonColor: "#3085d6",
      confirmButtonText: "Yes, delete it!",
      cancelButtonText: "Cancel",
    }).then((result) => {
      if (result.isConfirmed) {
        // Perform the delete action via AJAX
        $.ajax({
          url: "{{ url_for('home_blueprint.delete_report') }}", // Your Flask route for deleting
          type: "POST",
          data: { scan_id: scanId },
          success: function (response) {
            Swal.fire({
              title: "Deleted!",
              text: "Your report has been deleted.",
              icon: "success",
              timer: 2000,
              showConfirmButton: false,
            }).then(() => {
              // Reload the page or remove the deleted row
              location.reload();
            });
          },
          error: function (xhr, status, error) {
            Swal.fire({
              title: "Error",
              text: "Something went wrong: " + error,
              icon: "error",
            });
          },
        });
      }
    });
  }
</script>
{% endblock javascripts %}